[package]
name = "threshold-checker"
version = "0.1.0"
edition = "2024"

[lib]
name = "threshold_checker"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
